In [3]:
import numpy as np
import pandas as pd
import os
import re
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import statsmodels.api as sm

In [2]:
path_ref = 'C:\\Users\\tnguyen10\\OneDrive - Deloitte (O365D)\\Documents\\GitHub\\Thesis\\data\\refinitiv'

In [4]:
df_sample = pd.read_excel(os.path.join(path_ref,'sample.xlsx'))
df_sentiment = pd.read_csv('sentiment_scores.csv') #drop h&m and dhl
df_similarity = pd.read_csv('similarity_scores.csv')

In [7]:
df_sample

       company  resource use  emissions  environmental innovation  strategy
0          abb         62.39      99.39                     36.68     62.18
1       adidas         82.77      90.63                     80.68     76.89
2       airbus         99.43      97.09                     95.92     83.49
3        apple         98.51      97.50                     43.51     87.06
4        bayer         70.38      87.91                     82.94     95.75
..         ...           ...        ...                       ...       ...
59      veolia         74.49      79.00                     84.15     69.16
60  volkswagen         97.25      96.49                     92.69     96.07
61       volvo         96.45      88.41                     95.18     87.55
62     walmart         77.73      88.08                     76.81     87.01
63     inditex         97.61      99.33                     86.79     45.51

[64 rows x 5 columns]

In [9]:
df_sentiment

,company,0,1,2,3,4,5,6,total
0,henkel,-0.007491,-0.007629,0.012023,0.013756,0.004118,0.002563,-0.030222,-0.012884
1,general-mills,NaN,0.013966,-0.005795,0.019676,0.009944,0.004485,0.007125,0.049402
2,enel,0.000759,-0.018271,0.006222,0.001978,0.040981,0.019511,0.000442,0.051621
3,airbus,0.023659,0.003928,0.009152,-0.006690,0.046551,0.013631,0.009065,0.099296
4,eversource,0.005571,0.065910,0.009005,0.013049,0.077035,0.022740,0.000113,0.193422
...,...,...,...,...,...,...,...,...,...
58,dupont,0.006339,0.011108,0.008123,0.000057,0.081427,0.015871,0.031506,0.154431
59,mcdonald,-0.004740,0.000351,0.027431,0.019437,0.074865,0.019405,0.044869,0.181618
60,colgate,-0.002326,0.009628,0.007202,0.014026,0.021664,0.011243,0.060053,0.121489
61,nestle,-0.000185,0.000620,0.029275,0.013297,0.020408,0.046627,0.029277,0.139318
62,diageo,NaN,0.009781,-0.002372,0.029024,0.016686,-0.007609,-0.000226,0.045285

In [10]:
df_similarity

,company,0,1,2,3,4,5,6,average,rev_similarity
0,henkel,0.307193,0.441082,0.316931,0.471574,0.252742,0.515490,0.552531,0.408221,0.485468
1,general-mills,NaN,0.401772,0.317858,0.511924,0.268937,0.500265,0.260843,0.376933,0.603152
2,enel,0.307359,0.529861,0.247507,0.491178,0.324345,0.490653,0.330006,0.388701,0.558887
3,airbus,0.577002,0.485288,0.334677,0.580605,0.338507,0.485650,0.380358,0.454584,0.311079
4,eversource,0.257189,0.513299,0.231859,0.432165,0.351334,0.472154,0.213468,0.353067,0.692922
...,...,...,...,...,...,...,...,...,...,...
58,dupont,0.360307,0.412970,0.300349,0.470131,0.375814,0.574513,0.432614,0.418100,0.448309
59,mcdonald,0.358209,0.507266,0.480616,0.542530,0.401509,0.529817,0.588919,0.486981,0.189221
60,colgate,0.309629,0.231054,0.277209,0.442338,0.230000,0.505484,0.535156,0.361553,0.661002
61,nestle,0.255926,0.441334,0.359633,0.505296,0.327689,0.506255,0.540308,0.419492,0.443073
62,diageo,NaN,0.479605,0.346127,0.541078,0.228661,0.519638,0.519152,0.439044,0.369531

In [8]:
df_sentiment.rename(columns = {'Unnamed: 0': 'company'}, inplace = True)
df_similarity.rename(columns = {'Unnamed: 0': 'company'}, inplace = True)

In [11]:
df_sentiment['total'] = MinMaxScaler().fit_transform(np.array(df_sentiment['total']).reshape(-1,1))

### Preparing the Refinitiv data

In [12]:
df_sample['average_practice'] = df_sample[['resource use', 'emissions', 'environmental innovation']].replace(0, np.nan).mean(axis = 1)

In [14]:
df_sample['green_practice'] = StandardScaler().fit_transform(np.array(df_sample['average_practice']).reshape(-1,1))
df_sample['green_communication'] = StandardScaler().fit_transform(np.array(df_sample['strategy']).reshape(-1,1))
df_sample['discrepancy_index'] = df_sample['green_communication']-df_sample['green_practice']

In [17]:
df_linreg = pd.merge(df_sentiment, df_sample, how = 'left')

In [20]:
df_linreg['rev_similarity'] = df_similarity['rev_similarity']

In [22]:
df_linreg['discrepancy_index'] = MinMaxScaler().fit_transform(np.array(df_linreg['discrepancy_index']).reshape(-1,1))

In [31]:
df_linreg.drop(['h&m','dhl'], axis = 0, inplace = True)

KeyError: "['h&m', 'dhl'] not found in axis"

In [32]:
df_linreg

,company,0,1,2,3,4,5,6,total,resource use,emissions,environmental innovation,strategy,average_practice,green_practice,green_communication,discrepancy_index,rev_similarity
0,henkel,-0.007491,-0.007629,0.012023,0.013756,0.004118,0.002563,-0.030222,0.326188,99.53,82.43,27.62,95.75,69.860000,-0.944383,0.678493,0.763328,0.485468
1,general-mills,NaN,0.013966,-0.005795,0.019676,0.009944,0.004485,0.007125,0.423352,98.55,78.95,21.53,97.03,66.343333,-1.235565,0.768897,0.815389,0.603152
2,enel,0.000759,-0.018271,0.006222,0.001978,0.040981,0.019511,0.000442,0.426814,98.82,94.18,95.59,90.07,96.196667,1.236307,0.277326,0.411078,0.558887
3,airbus,0.023659,0.003928,0.009152,-0.006690,0.046551,0.013631,0.009065,0.501186,99.43,97.09,95.92,83.49,97.480000,1.342568,-0.187407,0.333176,0.311079
4,eversource,0.005571,0.065910,0.009005,0.013049,0.077035,0.022740,0.000113,0.648022,99.83,96.38,69.16,87.01,88.456667,0.595431,0.061204,0.469029,0.692922
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,dupont,0.006339,0.011108,0.008123,0.000057,0.081427,0.015871,0.031506,0.587196,59.66,26.73,69.96,99.51,52.116667,-2.413541,0.944055,1.000000,0.448309
59,mcdonald,-0.004740,0.000351,0.027431,0.019437,0.074865,0.019405,0.044869,0.629608,98.28,90.68,67.11,52.73,85.356667,0.338749,-2.359927,0.173727,0.189221
60,colgate,-0.002326,0.009628,0.007202,0.014026,0.021664,0.011243,0.060053,0.535808,99.24,93.57,90.48,97.08,94.430000,1.090026,0.772428,0.498584,0.661002
61,nestle,-0.000185,0.000620,0.029275,0.013297,0.020408,0.046627,0.029277,0.563621,88.82,91.31,85.93,84.52,88.686667,0.614475,-0.114660,0.442437,0.443073
62,diageo,NaN,0.009781,-0.002372,0.029024,0.016686,-0.007609,-0.000226,0.416930,81.25,95.05,55.93,97.54,77.410000,-0.319239,0.804917,0.695286,0.369531

In [24]:
X = df_linreg['total']
y = df_linreg['discrepancy_index']
X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:      discrepancy_index   R-squared:                       0.019
Model:                            OLS   Adj. R-squared:                  0.003
Method:                 Least Squares   F-statistic:                     1.208
Date:                Thu, 04 May 2023   Prob (F-statistic):              0.276
Time:                        16:50:31   Log-Likelihood:                 19.413
No. Observations:                  63   AIC:                            -34.83
Df Residuals:                      61   BIC:                            -30.54
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6166      0.073      8.393      0.000       0.470       0.764
total         -0.1536      0.140     -1.099      0.276      -0.433       0.126
==============================================================================
Omnibus:                        3.374   Durbin-Watson:                   2.420
Prob(Omnibus):                  0.185   Jarque-Bera (JB):                2.804
Skew:                          -0.242   Prob(JB):                        0.246
Kurtosis:                       3.914   Cond. No.                         7.71
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
X = df_linreg['rev_similarity']
y = df_linreg['discrepancy_index']
X2 = sm.add_constant(X)
est = sm.OLS(y, X2)
est2 = est.fit()
print(est2.summary())

MissingDataError: exog contains inf or nans

In [28]:
df_linreg[df_linreg['rev_similarity'].isnull()]

,company,0,1,2,3,4,5,6,total,resource use,emissions,environmental innovation,strategy,average_practice,green_practice,green_communication,discrepancy_index,rev_similarity
24,h&m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.346286,98.84,88.03,86.54,87.5,91.136667,0.817336,0.095811,0.443475,NaN